const std = @import("std");

const config = @import("config.zig");
const model = @import("model.zig");

const marker = "# @generated by gg; do not edit manually\n";
const lib_marker = "// @generated by gg; do not edit manually\n";

pub const ProblemProject = struct {
    dir: []const u8,
    solution_path: []const u8,
};

pub const SnippetSupport = struct {
    needs_solution_stub: bool = false,
    uses_list_node: bool = false,
    uses_tree_node: bool = false,
    needs_rc: bool = false,
    needs_ref_cell: bool = false,
};

pub fn ensureProblemProject(
    allocator: std.mem.Allocator,
    io: std.Io,
    workspace_root: []const u8,
    problem: model.ProblemSummary,
    detail: model.ProblemDetail,
) !ProblemProject {
    const snippet = detail.rustSnippet() orelse return error.MissingRustSnippet;
    try ensureWorkspaceRoot(allocator, io, workspace_root);
    try ensureSupportCrate(allocator, io, workspace_root);

    const dir_name = try crateDirName(allocator, problem.frontend_id, problem.slug);
    const rel = try std.fmt.allocPrint(allocator, "problems/{s}", .{dir_name});
    const dir = try config.pathJoin(allocator, &.{ workspace_root, rel });
    const src_dir = try config.pathJoin(allocator, &.{ dir, "src" });
    const solution_path = try config.pathJoin(allocator, &.{ src_dir, "solution.rs" });
    const lib_path = try config.pathJoin(allocator, &.{ src_dir, "lib.rs" });
    const manifest_path = try config.pathJoin(allocator, &.{ dir, "Cargo.toml" });

    try std.Io.Dir.cwd().createDirPath(io, src_dir);
    try updateWorkspaceManifest(allocator, io, workspace_root, rel);
    try writeGeneratedIfOwned(allocator, io, manifest_path, try renderProblemManifest(allocator, dir_name), marker);
    try writeGeneratedIfOwned(allocator, io, lib_path, try renderProblemLib(allocator, snippet.code), lib_marker);

    if (!try config.pathExists(io, solution_path)) {
        try std.Io.Dir.cwd().writeFile(io, .{
            .sub_path = solution_path,
            .data = try normalizeNewlines(allocator, snippet.code),
        });
    }

    return .{ .dir = dir, .solution_path = solution_path };
}

pub fn crateDirName(allocator: std.mem.Allocator, frontend_id: []const u8, slug: []const u8) ![]u8 {
    const clean_slug = try cleanIdent(allocator, slug);
    const numeric_id = std.fmt.parseInt(u32, frontend_id, 10) catch null;
    if (numeric_id) |id| {
        return std.fmt.allocPrint(allocator, "p{d:0>4}_{s}", .{ id, clean_slug });
    }
    const clean_id = try cleanIdent(allocator, frontend_id);
    return std.fmt.allocPrint(allocator, "p_{s}_{s}", .{ clean_id, clean_slug });
}

pub fn analyzeSnippet(allocator: std.mem.Allocator, src: []const u8) !SnippetSupport {
    const code = try stripLineComments(allocator, src);
    const uses_tree_node = mentionsSymbol(code, "TreeNode") and !definesSymbol(code, "TreeNode");
    const uses_list_node = mentionsSymbol(code, "ListNode") and !definesSymbol(code, "ListNode");
    const needs_solution_stub = mentionsSymbol(code, "Solution") and
        std.mem.indexOf(u8, code, "impl Solution") != null and
        !definesSymbol(code, "Solution");
    const needs_rc = mentionsSymbol(code, "Rc") and !importsSymbol(code, "Rc");
    const needs_ref_cell = mentionsSymbol(code, "RefCell") and !importsSymbol(code, "RefCell");

    return .{
        .needs_solution_stub = needs_solution_stub,
        .uses_list_node = uses_list_node,
        .uses_tree_node = uses_tree_node,
        .needs_rc = needs_rc,
        .needs_ref_cell = needs_ref_cell,
    };
}

fn ensureWorkspaceRoot(allocator: std.mem.Allocator, io: std.Io, root: []const u8) !void {
    const cwd = std.Io.Dir.cwd();
    try cwd.createDirPath(io, root);
    try cwd.createDirPath(io, try config.pathJoin(allocator, &.{ root, "problems" }));
}

fn ensureSupportCrate(allocator: std.mem.Allocator, io: std.Io, root: []const u8) !void {
    const dir = try config.pathJoin(allocator, &.{ root, "support" });
    const src = try config.pathJoin(allocator, &.{ dir, "src" });
    const manifest_path = try config.pathJoin(allocator, &.{ dir, "Cargo.toml" });
    const lib_path = try config.pathJoin(allocator, &.{ src, "lib.rs" });

    try std.Io.Dir.cwd().createDirPath(io, src);
    try updateWorkspaceManifest(allocator, io, root, "support");
    try writeGeneratedIfOwned(allocator, io, manifest_path, renderSupportManifest(), marker);
    try writeGeneratedIfOwned(allocator, io, lib_path, renderSupportLib(), lib_marker);
}

fn renderSupportManifest() []const u8 {
    return marker ++
        \\[package]
        \\name = "leetcode-support"
        \\version = "0.1.0"
        \\edition = "2024"
        \\
    ;
}

fn renderSupportLib() []const u8 {
    return lib_marker ++
        \\#![allow(dead_code)]
        \\
        \\use std::cell::RefCell;
        \\use std::rc::Rc;
        \\
        \\#[derive(PartialEq, Eq, Clone, Debug)]
        \\pub struct ListNode {
        \\    pub val: i32,
        \\    pub next: Option<Box<ListNode>>,
        \\}
        \\
        \\impl ListNode {
        \\    #[inline]
        \\    pub fn new(val: i32) -> Self {
        \\        Self { val, next: None }
        \\    }
        \\}
        \\
        \\#[derive(PartialEq, Eq, Clone, Debug)]
        \\pub struct TreeNode {
        \\    pub val: i32,
        \\    pub left: Option<Rc<RefCell<TreeNode>>>,
        \\    pub right: Option<Rc<RefCell<TreeNode>>>,
        \\}
        \\
        \\impl TreeNode {
        \\    #[inline]
        \\    pub fn new(val: i32) -> Self {
        \\        Self {
        \\            val,
        \\            left: None,
        \\            right: None,
        \\        }
        \\    }
        \\}
        \\
    ;
}

fn renderProblemManifest(allocator: std.mem.Allocator, name: []const u8) ![]u8 {
    return std.fmt.allocPrint(
        allocator,
        marker ++
            \\[package]
            \\name = "{s}"
            \\version = "0.1.0"
            \\edition = "2024"
            \\
            \\[dependencies]
            \\leetcode-support = {{ path = "../../support" }}
            \\
        ,
        .{name},
    );
}

fn renderProblemLib(allocator: std.mem.Allocator, snippet: []const u8) ![]u8 {
    const support = try analyzeSnippet(allocator, snippet);
    var out: std.Io.Writer.Allocating = .init(allocator);
    const w = &out.writer;

    try w.writeAll(lib_marker);
    try w.writeAll("#![allow(dead_code)]\n");
    try w.writeAll("#![allow(unused_imports)]\n\n");

    if (support.uses_list_node and support.uses_tree_node) {
        try w.writeAll("use leetcode_support::{ListNode, TreeNode};\n");
    } else if (support.uses_list_node) {
        try w.writeAll("use leetcode_support::ListNode;\n");
    } else if (support.uses_tree_node) {
        try w.writeAll("use leetcode_support::TreeNode;\n");
    }
    if (support.needs_ref_cell) try w.writeAll("use std::cell::RefCell;\n");
    if (support.needs_rc) try w.writeAll("use std::rc::Rc;\n");
    if (support.needs_solution_stub) try w.writeAll("pub struct Solution;\n");

    if (out.written()[out.written().len - 1] != '\n' or out.written()[out.written().len - 2] != '\n') {
        try w.writeByte('\n');
    }
    try w.writeAll("include!(\"solution.rs\");\n");
    return out.toOwnedSlice();
}

fn updateWorkspaceManifest(
    allocator: std.mem.Allocator,
    io: std.Io,
    root: []const u8,
    member: []const u8,
) !void {
    const manifest_path = try config.pathJoin(allocator, &.{ root, "Cargo.toml" });
    var members: std.ArrayList([]const u8) = .empty;
    if (try config.pathExists(io, manifest_path)) {
        const raw = try std.Io.Dir.cwd().readFileAlloc(io, manifest_path, allocator, .limited(1024 * 1024));
        try parseWorkspaceMembers(allocator, raw, &members);
    }
    try members.append(allocator, member);
    std.mem.sort([]const u8, members.items, {}, struct {
        fn lessThan(_: void, a: []const u8, b: []const u8) bool {
            return std.mem.lessThan(u8, a, b);
        }
    }.lessThan);

    var deduped: std.ArrayList([]const u8) = .empty;
    var last: ?[]const u8 = null;
    for (members.items) |m| {
        if (last == null or !std.mem.eql(u8, last.?, m)) {
            try deduped.append(allocator, m);
            last = m;
        }
    }

    var out: std.Io.Writer.Allocating = .init(allocator);
    const w = &out.writer;
    try w.writeAll(marker);
    try w.writeAll("[workspace]\n");
    try w.writeAll("members = [\n");
    for (deduped.items) |m| try w.print("  \"{s}\",\n", .{m});
    try w.writeAll("]\n");
    try w.writeAll("resolver = \"2\"\n");
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = manifest_path, .data = out.written() });
}

fn parseWorkspaceMembers(
    allocator: std.mem.Allocator,
    raw: []const u8,
    out: *std.ArrayList([]const u8),
) !void {
    const start = std.mem.indexOf(u8, raw, "members") orelse return;
    const open_rel = std.mem.indexOfScalar(u8, raw[start..], '[') orelse return;
    const open = start + open_rel + 1;
    const close_rel = std.mem.indexOfScalar(u8, raw[open..], ']') orelse return;
    const body = raw[open .. open + close_rel];

    var i: usize = 0;
    while (i < body.len) : (i += 1) {
        if (body[i] != '"') continue;
        const item_start = i + 1;
        i = item_start;
        while (i < body.len and body[i] != '"') : (i += 1) {}
        if (i <= body.len) try out.append(allocator, body[item_start..i]);
    }
}

fn writeGeneratedIfOwned(
    allocator: std.mem.Allocator,
    io: std.Io,
    path: []const u8,
    data: []const u8,
    expected_marker: []const u8,
) !void {
    const exists = try config.pathExists(io, path);
    if (exists) {
        const raw = try std.Io.Dir.cwd().readFileAlloc(io, path, allocator, .limited(4 * 1024 * 1024));
        if (!std.mem.startsWith(u8, raw, expected_marker)) return;
    }
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = data });
}

fn normalizeNewlines(allocator: std.mem.Allocator, src: []const u8) ![]u8 {
    var out: std.Io.Writer.Allocating = .init(allocator);
    var i: usize = 0;
    while (i < src.len) : (i += 1) {
        if (src[i] == '\r') {
            if (i + 1 < src.len and src[i + 1] == '\n') continue;
            try out.writer.writeByte('\n');
        } else {
            try out.writer.writeByte(src[i]);
        }
    }
    if (out.written().len == 0 or out.written()[out.written().len - 1] != '\n') {
        try out.writer.writeByte('\n');
    }
    return out.toOwnedSlice();
}

fn cleanIdent(allocator: std.mem.Allocator, input: []const u8) ![]u8 {
    var out: std.Io.Writer.Allocating = .init(allocator);
    var prev_us = false;
    for (input) |ch| {
        const c = std.ascii.toLower(ch);
        if (std.ascii.isAlphanumeric(c)) {
            try out.writer.writeByte(c);
            prev_us = false;
        } else if (!prev_us) {
            try out.writer.writeByte('_');
            prev_us = true;
        }
    }

    const raw = out.written();
    const trimmed = std.mem.trim(u8, raw, "_");
    if (trimmed.len == 0) return allocator.dupe(u8, "problem");
    return allocator.dupe(u8, trimmed);
}

fn stripLineComments(allocator: std.mem.Allocator, src: []const u8) ![]u8 {
    var out: std.Io.Writer.Allocating = .init(allocator);
    var it = std.mem.splitScalar(u8, src, '\n');
    while (it.next()) |line| {
        if (std.mem.startsWith(u8, std.mem.trimStart(u8, line, " \t"), "//")) continue;
        try out.writer.writeAll(line);
        try out.writer.writeByte('\n');
    }
    return out.toOwnedSlice();
}

fn mentionsSymbol(code: []const u8, name: []const u8) bool {
    var i: usize = 0;
    while (i < code.len) {
        while (i < code.len and !isIdentChar(code[i])) : (i += 1) {}
        const start = i;
        while (i < code.len and isIdentChar(code[i])) : (i += 1) {}
        if (start != i and std.mem.eql(u8, code[start..i], name)) return true;
    }
    return false;
}

fn definesSymbol(code: []const u8, name: []const u8) bool {
    var it = std.mem.splitScalar(u8, code, '\n');
    while (it.next()) |line| {
        const trimmed = std.mem.trimStart(u8, line, " \t");
        if (startsWithDecl(trimmed, "struct", name)) return true;
        if (startsWithDecl(trimmed, "pub struct", name)) return true;
        if (startsWithDecl(trimmed, "enum", name)) return true;
        if (startsWithDecl(trimmed, "pub enum", name)) return true;
        if (startsWithDecl(trimmed, "type", name)) return true;
        if (startsWithDecl(trimmed, "pub type", name)) return true;
    }
    return false;
}

fn startsWithDecl(line: []const u8, prefix: []const u8, name: []const u8) bool {
    if (!std.mem.startsWith(u8, line, prefix)) return false;
    var rest = line[prefix.len..];
    if (rest.len == 0 or !std.ascii.isWhitespace(rest[0])) return false;
    rest = std.mem.trimStart(u8, rest, " \t");
    return std.mem.startsWith(u8, rest, name);
}

fn importsSymbol(code: []const u8, name: []const u8) bool {
    var it = std.mem.splitScalar(u8, code, '\n');
    while (it.next()) |line| {
        const trimmed = std.mem.trimStart(u8, line, " \t");
        if (std.mem.startsWith(u8, trimmed, "use ") and std.mem.indexOf(u8, trimmed, name) != null) {
            return true;
        }
    }
    return false;
}

fn isIdentChar(c: u8) bool {
    return std.ascii.isAlphanumeric(c) or c == '_';
}

test "crate dir uses zero padded numeric ids" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const allocator = arena_state.allocator();

    try std.testing.expectEqualStrings("p0001_two_sum", try crateDirName(allocator, "1", "two-sum"));
    try std.testing.expectEqualStrings("p_lcr_012_foo", try crateDirName(allocator, "LCR 012", "foo"));
}

test "snippet analysis adds missing leetcode helper imports" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const allocator = arena_state.allocator();

    const s = try analyzeSnippet(
        allocator,
        "impl Solution { pub fn f(x: Option<Rc<RefCell<TreeNode>>>) {} }",
    );
    try std.testing.expect(s.needs_solution_stub);
    try std.testing.expect(s.uses_tree_node);
    try std.testing.expect(s.needs_rc);
    try std.testing.expect(s.needs_ref_cell);
}

test "project generation preserves existing solution and is cargo metadata friendly" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const allocator = arena_state.allocator();

    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const root = try config.pathJoin(allocator, &.{ ".zig-cache", "tmp", tmp.sub_path[0..], "workspace" });

    const summary = model.ProblemSummary{
        .frontend_id = "1",
        .question_id = 1,
        .slug = "two-sum",
        .title = "Two Sum",
        .difficulty = .easy,
    };
    const detail = model.ProblemDetail{
        .frontend_id = "1",
        .question_id = 1,
        .slug = "two-sum",
        .title = "Two Sum",
        .code_snippets = &.{.{
            .lang = "Rust",
            .lang_slug = "rust",
            .code = "impl Solution { pub fn two_sum(nums: Vec<i32>, target: i32) -> Vec<i32> { vec![] } }",
        }},
    };

    const project = try ensureProblemProject(allocator, std.testing.io, root, summary, detail);
    try std.Io.Dir.cwd().writeFile(std.testing.io, .{ .sub_path = project.solution_path, .data = "custom\n" });
    _ = try ensureProblemProject(allocator, std.testing.io, root, summary, detail);
    const solution = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, project.solution_path, allocator, .limited(1024));
    try std.testing.expectEqualStrings("custom\n", solution);

    const manifest = try config.pathJoin(allocator, &.{ root, "Cargo.toml" });
    const result = std.process.run(allocator, std.testing.io, .{
        .argv = &.{ "cargo", "metadata", "--manifest-path", manifest, "--format-version", "1", "--no-deps" },
        .stdout_limit = .limited(1024 * 1024),
        .stderr_limit = .limited(1024 * 1024),
    }) catch |err| switch (err) {
        error.FileNotFound => return error.SkipZigTest,
        else => |e| return e,
    };
    try std.testing.expectEqual(std.process.Child.Term{ .exited = 0 }, result.term);
}
